export default {
  SMURFS: "SMURFS",
  FETCHING_SMURFS: "FETCHING_SMURFS",
  ADDING_SMURFS: "ADDING_SMURFS",
  UPDATING_SMURFS: "UPDATING_SMURFS",
  DELETING_SMURFS: "DELETING_SMURFS",
  ERROR: "ERROR"
};
